-- SELECT CNAME, AMOUNT
-- FROM CUSTOMER, ORDERS;
SELECT C.CNAME, O.AMOUNT
FROM CUSTOMER C
INNER JOIN ORDER O
ON C.CID = O.OID

-- SELECT CNAME
-- FROM CUSTOMER, ORDERS
-- WHERE CID IS NULL
SELECT C.CNAME
FROM CUSTOMER C
LEFT JOIN ORDER O
ON C.CID = O.OID
WHERE O.CID IS NULL;


-- SELECT CNAME, SUM(AMOUNT)
-- FROM CUSTOMER, ORDERS
-- GROUP BY CID;
SELECT C.CNAME, SUM(O.AMOUNT)
FROM CUSTOMER C
INNER JOIN ORDER O
ON C.CID = O.OID
GROUP BY CNAME

-- INNER JOIN - Use to Join record which is similiar in both table
-- LEFT JOIN - use to join record which is present on in first table